name: predictive-autoscaling
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgomp=13.2.0=h807b86a_2
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.43.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.4=hd590300_0
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.8.18=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=h2797004_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - cmdstanpy==1.2.0
      - comm==0.1.4
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - fqdn==1.5.1
      - holidays==0.35
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - ipykernel==6.26.0
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jplephem==2.19
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.5.0
      - jupyter-console==6.6.3
      - jupyter-core==5.4.0
      - jupyter-events==0.8.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.9.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lunardate==0.2.0
      - markupsafe==2.1.3
      - matplotlib==3.3.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - overrides==7.4.0
      - packaging==23.2
      - pandas==1.2.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.11.0
      - plotly==5.18.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - prophet==1.1.5
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycalverter==1.6.1
      - pycparser==2.21
      - pygments==2.16.1
      - pyluach==2.2.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.1
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.6
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - sgp4==2.22
      - six==1.16.0
      - skyfield==1.46
      - skyfield-data==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - stanio==0.3.0
      - tenacity==8.2.3
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - timeseries-generator==0.1.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.12.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - uri-template==1.3.0
      - urllib3==2.0.7
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - widgetsnbextension==4.0.9
      - workalendar==15.0.1
      - zipp==3.17.0
